-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 11:55:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema -- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 11:55:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webPythonProjetoEstudo2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webPythonProjetoEstudo2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webPythonProjetoEstudo2019` DEFAULT CHARACTER SET latin1 ;
USE `webPythonProjetoEstudo2019` ;

-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `observacao` VARCHAR(200) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(255) NULL,
  `grupo` CHAR(5) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_pedidos` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_tb_pedidos_tb_clientes_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_tb_pedidos_tb_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `db_abc_bolinhas`.`tb_clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_produtos` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `imagem` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_pedido_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_pedido_produtos` (
  `id_pedido` INT(11) NOT NULL,
  `id_produto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `valor` DECIMAL(10,0) NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `fk_table1_tb_pedidos1_idx` (`id_pedido` ASC),
  INDEX `fk_table1_tb_produtos1_idx` (`id_produto` ASC),
  CONSTRAINT `fk_table1_tb_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `webPythonProjetoEstudo2019`.`tb_pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tb_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `webPythonProjetoEstudo2019`.`tb_produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `grupo` CHAR(5) NOT NULL DEFAULT 'admin',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webPythonProjetoEstudo2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webPythonProjetoEstudo2019` DEFAULT CHARACTER SET latin1 ;
USE `webPythonProjetoEstudo2019` ;

-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_clientes` (
  `id_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `observacao` VARCHAR(200) NULL DEFAULT NULL,
  `cep` CHAR(8) NULL DEFAULT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `telefone` CHAR(11) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_pedidos` (
  `id_pedido` INT(11) NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_tb_pedidos_tb_clientes_idx` (`id_cliente` ASC) ,
  CONSTRAINT `fk_tb_pedidos_tb_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `webPythonProjetoEstudo2019`.`tb_clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_produtos` (
  `id_produto` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `imagem` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `webPythonProjetoEstudo2019`.`tb_pedido_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_pedido_produtos` (
  `id_pedido` INT(11) NOT NULL,
  `id_produto` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `valor` DECIMAL(10,0) NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `fk_table1_tb_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_table1_tb_produtos1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_table1_tb_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `webPythonProjetoEstudo2019`.`tb_pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_tb_produtos1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `webPythonProjetoEstudo2019`.`tb_produtos` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table ``.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webPythonProjetoEstudo2019`.`tb_usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `grupo` CHAR(5) NOT NULL DEFAULT 'admin',
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;